# Permalinks
permalink:           pretty

# Setup
title:               Herb Susmann
tagline:             Software Developer
url:                 http://herbps10.github.io
paginate:            5
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Herb Susmann
  url:               https://twitter.com/herbps10
  email:             herbps10@gmail.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/herbps10/herbps10.github.io

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
